spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: chimanloo1004
    driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    settings:
      classic_compatible: true # 处理空值
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##

  redis:
    host: 127.0.0.1
    port: 6379

  data:
    elasticsearch:
      cluster-name:
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true

  rabbitmq:
    username: guest
    password: guest
    addresses: 127.0.0.1

im:
  server:
    port: 9326

file:
  upload:
    dir: ${user.dir}/upload

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml